[package]
name = "imgoptim"
version = "0.2.13"
edition = "2024"
description = "Image Optimization"
authors = ["yoshitaka-k"]
license = "Apache-2.0"

[package.metadata.bundle]
identifier = "jp.ktgwya.imgoptim"
name = "Img Optim"
icon = ["assets/icon.png"]
category = "Utility"
short_description = "Image Optimization"
linux_use_terminal = false
deb_depends = [
    "libgtk-3-0",
    "libxcb-render0",
    "libxcb-shape0",
    "libxcb-xfixes0",
    "libxkbcommon0",
    "libvulkan1",
    "libssl3",
]

[package.metadata.winresource]
ProductName = "Img Optim"
FileDescription = "Image Optimization"
OriginalFilename = "Img Optim.exe"

[build-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
winresource = "0.1.31"
image = "0.25.10"
ico = "0.5"

[dependencies]
egui = "0.36.1"
egui_extras = { version = "0.36.1", features = ["all_loaders"] }
eframe = { version = "0.36.1", features = ["persistence"] }
log = "0.4.33"
env_logger = "0.11.11"
getset = "0.1.7"
image = "0.25.10"
rfd = "0.17.2"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
oxipng = { version = "10.2.0", default-features = false, features = ["parallel"] }
